Name:           ros-indigo-typelib
Version:        2.8.0
Release:        0%{?dist}
Summary:        ROS typelib package

Group:          Development/Libraries
License:        CeCILL-B (BSD-like)
Source0:        %{name}-%{version}.tar.gz

Requires:       boost-devel
Requires:       gccxml
Requires:       libxml2-devel
Requires:       ros-indigo-catkin
Requires:       ros-indigo-utilrb
Requires:       rubygem-facets
BuildRequires:  boost-devel
BuildRequires:  cmake
BuildRequires:  gccxml
BuildRequires:  libxml2-devel
BuildRequires:  pkgconfig
BuildRequires:  ros-indigo-catkin
BuildRequires:  ros-indigo-utilrb
BuildRequires:  rubygem-facets

%description
This library offers an introspection mechanism for C/C++ value-types. I.e. it
offers a way to represent types, and to manipulate in-memory values that are
instances of those types. A Ruby binding is included, which gives a fast and
transparent modification of C/C++ in-memory types from Ruby.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Mon Jan 26 2015 OCL Development Team <orocos-dev@lists.mech.kuleuven.be> - 2.8.0-0
- Autogenerated by Bloom

